export const META_KEYWORDS = [
  "calçados",
  "loja de calçados",
  "roupas",
  "moda",
  "loja de moda",
  "calçados femininos",
  "calçados masculinos",
  "tênis",
  "sandálias",
  "sapatos sociais",
  "botas femininas",
  "botas masculinas",
  "loja de sapatos",
  "atendimento personalizado",
  "consultora de moda",
  "tendências de moda para calçados",
  "looks completos com calçados e roupas",
  "lojas de calçados próximas a mim",
  "compre agora seu sapato ideal",
  "fale com nossa consultora de moda",
  "descubra os melhores calçados para você",
  "escolha seu look com ajuda de especialistas",
  "encontre seu estilo com nosso atendimento online",
  "clique no WhatsApp e fale com uma consultora",
];
